// Generated by CoffeeScript 1.6.3
(function() {
  define(['module', 'odo/express/configure', 'odo/express/app'], function(module, configure, app) {
    var components;
    components = [];
    return {
      web: function() {
        configure.route('/odo/durandal', configure.modulepath(module.uri) + '/public');
        return app.get('/odo/components', function(req, res) {
          return res.send(components);
        });
      },
      register: function(component) {
        return components.push(component);
      }
    };
  });

}).call(this);
