// Generated by CoffeeScript 1.7.1
(function() {
  define(['module', 'odo/express'], function(module, express) {
    var components;
    components = [];
    return {
      web: function() {
        express.route('/odo/durandal', express.modulepath(module.uri) + '/public');
        return express.get('/odo/components', function(req, res) {
          return res.send(components);
        });
      },
      register: function(component) {
        return components.push(component);
      }
    };
  });

}).call(this);
