// Generated by IcedCoffeeScript 1.4.0c
(function() {
  var express;

  express = require('express');

  module.exports = {
    init: function(app) {
      app.peek.get('/test**', function(req, res, next) {
        res.locals.user = {
          name: 'Thomas Coats',
          title: 'Master'
        };
        return next();
      });
      app.peek.get('/test**', function(req, res, next) {
        return res.render({
          view: 'test/display',
          data: {
            name: 'Thomas'
          },
          result: function(error, html) {
            if (error != null) throw error;
            res.locals.content = html;
            return next();
          }
        });
      });
      app.peek.get('/test**', function(req, res, next) {
        res.locals.partials.menu = 'menu';
        return next();
      });
      return app.get('/test', function(req, res) {
        return res.render({
          view: 'test/layout',
          data: {
            title: 'Display'
          }
        });
      });
    }
  };

}).call(this);
