// Generated by IcedCoffeeScript 1.4.0c
(function() {
  var express, iced, __iced_k, __iced_k_noop;

  iced = require('iced-coffee-script').iced;
  __iced_k = __iced_k_noop = function() {};

  express = require('express');

  module.exports = {
    init: function(app) {
      app.peek.get('/test', function(req, res, next) {
        var error, html, ___iced_passed_deferral, __iced_deferrals, __iced_k,
          _this = this;
        __iced_k = __iced_k_noop;
        ___iced_passed_deferral = iced.findDeferral(arguments);
        (function(__iced_k) {
          __iced_deferrals = new iced.Deferrals(__iced_k, {
            parent: ___iced_passed_deferral,
            filename: "/Users/tcoats/Source/odo/test/test.coffee"
          });
          res.render({
            view: 'test/display',
            data: {
              name: 'Thomas'
            },
            result: __iced_deferrals.defer({
              assign_fn: (function() {
                return function() {
                  error = arguments[0];
                  return html = arguments[1];
                };
              })(),
              lineno: 11
            })
          });
          __iced_deferrals._fulfill();
        })(function() {
          res.locals.content = html;
          return next();
        });
      });
      return app.get('/test', function(req, res) {
        return res.render({
          view: 'test/layout',
          data: {
            title: 'Display'
          }
        });
      });
    }
  };

}).call(this);
