// Generated by IcedCoffeeScript 1.4.0c
(function() {
  var dropbox, express;

  express = require('express');

  dropbox = require('dropbox-redis-cache');

  module.exports = {
    init: function(app) {
      return app.get('/test', function(req, res) {
        var client;
        if (req.user == null) {
          res.send('Not logged in');
          return;
        }
        client = new dropbox.Client({
          key: app.get('dropbox key'),
          secret: app.get('dropbox secret'),
          token: req.user.token,
          tokenSecret: req.user.tokenSecret,
          uid: req.user._json.uid
        });
        return client.readdir('/Knowledge/Brain Dump', function(error, pages) {
          return res.send(pages.join(', '));
        });
      });
    }
  };

}).call(this);
