// Generated by CoffeeScript 1.7.1
(function() {
  define(['module', 'odo/express'], function(module, express) {
    var Bower;
    return Bower = (function() {
      function Bower() {}

      Bower.prototype.web = function() {
        express.route('/', express.modulepath(module.uri) + '/../../../bower_components');
        return express.route('/odo', express.modulepath(module.uri) + '/public');
      };

      return Bower;

    })();
  });

}).call(this);
