// Generated by CoffeeScript 1.6.3
(function() {
  define(['module', 'odo/express/configure'], function(module, configure) {
    var Bower;
    return Bower = (function() {
      function Bower() {}

      Bower.prototype.web = function() {
        return configure.route('/', configure.modulepath(module.uri) + '/../../../bower_components');
      };

      return Bower;

    })();
  });

}).call(this);
