// Generated by IcedCoffeeScript 1.4.0a
(function() {
  var _;

  _ = require('underscore');

  module.exports = {
    init: function(app) {
      var load;
      load = function(req, res) {
        return res.render('layout', {
          title: 'Test',
          partials: {
            content: 'example/test'
          }
        });
      };
      app.get('/login-example', load);
      return app.post('/login-example', function(req, res) {
        console.log('Username: ' + req.body.username);
        return load(req, res);
      });
    }
  };

}).call(this);
