// Generated by IcedCoffeeScript 1.3.3f
(function() {
  var App, Measurement;

  Measurement = (function() {

    function Measurement(name, skill, output, group, delivery) {
      if (name == null) name = 'default';
      if (skill == null) skill = 0.05;
      if (output == null) output = 0.05;
      if (group == null) group = 0.05;
      if (delivery == null) delivery = 0.05;
      this.Name = ko.observable(name);
      this.Skill = ko.observable(skill);
      this.Output = ko.observable(output);
      this.Group = ko.observable(group);
      this.Delivery = ko.observable(delivery);
    }

    Measurement.prototype.total = function() {
      return this.Skill() + this.Output() + this.Group() + this.Delivery();
    };

    return Measurement;

  })();

  App = (function() {

    function App() {
      this.Measurements = ko.observableArray();
      this.SortedMeasurements = ko.dependentObservable((function() {
        return this.Measurements.slice().sort(function(a, b) {
          return b.total() - a.total();
        });
      }), this);
    }

    App.prototype.addMeasurement = function(measurement) {
      this.Measurements.push(measurement);
      return this;
    };

    return App;

  })();

  $(function() {
    var app;
    app = new App;
    app.addMeasurement(new Measurement('Bob', 0.1, 0.2, 0.5, 0.4));
    app.addMeasurement(new Measurement('Maggie', 0.2, 0.1, 0.3, 0.3));
    app.addMeasurement(new Measurement('Steven', 1, 1, 0, 1));
    app.addMeasurement(new Measurement('Dreyfus', 0.4, 0.1, 0.3, 0.4));
    app.addMeasurement(new Measurement('Edward', 0.3, 0.3, 0.1, 0.2));
    app.addMeasurement(new Measurement('Fiona', 0.0, 0.0, 0.0, 0.0));
    app.addMeasurement(new Measurement('Garry', .1, 0.3, 0.4, 0.2));
    app.addMeasurement(new Measurement('Hayden', 0.2, 0.2, 0.3, 0.1));
    app.addMeasurement(new Measurement('Tim', 0.3, 0.3, 0.2, 0.1));
    app.addMeasurement(new Measurement('Jane', 0.4, 0.2, 0.1, 0.1));
    app.addMeasurement(new Measurement('Ken', 0.5, 0.5, 0.4, 0.1));
    app.addMeasurement(new Measurement('Liam', 0.1, 0.1, 0.1, 0.1));
    app.addMeasurement(new Measurement('Mirriam', 0.3, 0.0, 0.2, 0.1));
    ko.applyBindings(app);
    window.app = app;
    return window.Measurement = Measurement;
  });

}).call(this);
