// Generated by CoffeeScript 1.7.1
define(['module', 'fs', 'path', 'cson'], function(module, fs, path, CSON) {
  var copy, domainenv, domainenvblob, domainenvvar, envdomain, globalenv, globalenvblob, globalenvvar, localfile, object, parse, result, template, _i, _len, _ref;
  template = {
    redis: {
      'use socket': true
    },
    express: {
      'session key': true,
      'cookie secret': true,
      'session secret': true,
      'allowed cross domains': true,
      'port': true
    },
    passport: {
      twitter: {
        'consumer key': true,
        'consumer secret': true,
        host: true
      },
      facebook: {
        'app id': true,
        'app secret': true,
        host: true
      },
      google: {
        realm: true,
        host: true
      },
      metocean: {
        'client id': true,
        'client secret': true,
        host: true,
        'authorization url': true,
        'token url': true
      }
    },
    mandrill: {
      'api key': true
    },
    odo: {
      auth: {
        signout: true,
        metocean: {
          successRedirect: true,
          failureRedirect: true
        }
      }
    }
  };
  copy = function(source, target) {
    var key, value, _results;
    _results = [];
    for (key in source) {
      value = source[key];
      if (typeof value === 'object') {
        if (target[key] == null) {
          target[key] = {};
        }
        _results.push(copy(value, target[key]));
      } else {
        _results.push(target[key] = value);
      }
    }
    return _results;
  };
  parse = function(prefix, node, result) {
    var envkey, key, value;
    if (result == null) {
      result = {};
    }
    for (key in node) {
      value = node[key];
      envkey = "" + prefix + (key.toUpperCase().replace(/[ -]/g, '_'));
      if (typeof value === 'object') {
        if (result[key] == null) {
          result[key] = {};
        }
        parse("" + envkey + "_", value, result[key]);
      } else if (value === true && (process.env[envkey] != null)) {
        console.log("Reading " + envkey);
        result[key] = process.env[envkey];
      }
    }
    return result;
  };
  localfile = CSON.parseFileSync(path.join(path.dirname(module.uri), '../../config.cson'));
  localfile["package"] = JSON.parse(fs.readFileSync(path.join(path.dirname(module.uri), '../../package.json')));
  envdomain = localfile.odo.domain.toUpperCase().replace(/[ -]/g, '_');
  globalenvvar = 'ODO_CONFIG';
  globalenvblob = {};
  if (process.env[globalenvvar] != null) {
    globalenvblob = CSON.parseSync(process.env[globalenvvar]);
  }
  globalenv = parse('', template);
  domainenvvar = "" + envdomain + "_ODO_CONFIG";
  domainenvblob = {};
  if (process.env[domainenvvar] != null) {
    domainenvblob = CSON.parseSync(process.env[domainenvvar]);
  }
  domainenv = parse("" + envdomain + "_", template);
  result = localfile;
  _ref = [globalenvblob, globalenv, domainenvblob, domainenv];
  for (_i = 0, _len = _ref.length; _i < _len; _i++) {
    object = _ref[_i];
    copy(object, result);
  }
  return result;
});
