// Generated by CoffeeScript 1.8.0
define(['odo/config', 'redwire-consul', 'CSON'], function(config, consul, CSON) {
  return function(httpAddr, callback) {
    var firstRun, watch;
    firstRun = true;
    return watch = new consul.KV(httpAddr, "" + config.odo.domain + "/odo-config", function(configurations) {
      var c, _i, _len;
      for (_i = 0, _len = configurations.length; _i < _len; _i++) {
        c = configurations[_i];
        config["import"](CSON.parseSync(c.Value));
      }
      if (firstRun) {
        firstRun = false;
        return callback();
      }
    });
  };
});
