// Generated by CoffeeScript 1.7.1
(function() {
  define(['cson'], function(CSON) {
    return function(path, cb) {
      return CSON.parseFile(path, function(err, data) {
        return cb(data);
      });
    };
  });

}).call(this);
