// Generated by CoffeeScript 1.7.1
(function() {
  define(['odo/express'], function(express) {
    var components;
    components = [];
    return {
      web: function() {
        return express.get('/odo/components', function(req, res) {
          return res.send(components);
        });
      },
      register: function(component) {
        return components.push(component);
      }
    };
  });

}).call(this);
