// Generated by CoffeeScript 1.9.1
var bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty,
  indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

define(['odo/config', 'odo/recorder'], function(config, Recorder) {
  var Express;
  Express = (function(superClass) {
    extend(Express, superClass);

    Express.prototype.configMethods = ['route', 'use'];

    Express.prototype.appMethods = ['get', 'post', 'put', 'delete', 'engine', 'set'];

    function Express() {
      this.web = bind(this.web, this);
      var i, j, len, len1, method, ref, ref1;
      ref = this.configMethods;
      for (i = 0, len = ref.length; i < len; i++) {
        method = ref[i];
        this[method] = this._record(method);
      }
      ref1 = this.appMethods;
      for (j = 0, len1 = ref1.length; j < len1; j++) {
        method = ref1[j];
        this[method] = this._record(method);
      }
      Express.__super__.constructor.call(this);
    }

    Express.prototype.modulepath = function(uri) {
      var items;
      items = uri.split('/');
      items.pop();
      return items.join('/');
    };

    Express.prototype.web = function() {
      var RedisStore, alloweddomains, bodyParser, express, http, key, port, ref, ref1, ref2, session, sessionConfig, sessionOptions, value;
      http = require('http');
      express = require('express');
      this.app = express();
      ref = config.express;
      for (key in ref) {
        value = ref[key];
        this.app.set(key, value);
      }
      this.app.use(require('compression')());
      bodyParser = require('body-parser');
      this.app.use(bodyParser.urlencoded({
        extended: true
      }));
      this.app.use(bodyParser.json());
      if (this.app.get('upload directory') != null) {
        this.app.use(require('multer')({
          dest: this.app.get('upload directory')
        }));
      }
      this.app.use(require('method-override')());
      this.app.use(require('cookie-parser')(this.app.get('cookie secret')));
      if ((this.app.get('use redis sessions') != null) && this.app.get('use redis sessions')) {
        session = require('express-session');
        RedisStore = require('connect-redis')(session);
        sessionOptions = {
          secret: this.app.get('session secret'),
          saveUninitialized: true,
          resave: true
        };
        if (config.redis.socket != null) {
          sessionOptions.store = new RedisStore({
            socket: config.redis.socket,
            prefix: config.odo.domain + ":sess:"
          });
        } else {
          sessionOptions.store = new RedisStore({
            host: config.redis.host,
            port: config.redis.port,
            prefix: config.odo.domain + ":sess:"
          });
        }
        sessionConfig = (ref1 = config.express) != null ? ref1.session : void 0;
        if (sessionConfig != null) {
          if (sessionConfig.rolling != null) {
            sessionOptions.rolling = sessionConfig.rolling;
          }
          if (sessionConfig.name != null) {
            sessionOptions.name = sessionConfig.name;
          }
          if (sessionConfig.cookie != null) {
            sessionOptions.cookie = {};
            ref2 = sessionConfig.cookie;
            for (key in ref2) {
              value = ref2[key];
              sessionOptions.cookie[key] = value;
            }
          }
        }
        this.app.use(session(sessionOptions));
      } else {
        this.app.use(require('cookie-session')({
          key: this.app.get('session key'),
          secret: this.app.get('session secret')
        }));
      }
      if (this.app.get('allowed cross domains') != null) {
        alloweddomains = this.app.get('allowed cross domains').split(' ');
        this.app.use((function(_this) {
          return function(req, res, next) {
            var referrer, u;
            referrer = req.protocol + "://" + req.hostname;
            if (req.header('referer') != null) {
              u = url.parse(req.header('referer'));
              referrer = u.protocol + "//" + u.host;
            }
            if (indexOf.call(alloweddomains, referrer) < 0) {
              return next();
            }
            res.header('Access-Control-Allow-Origin', referrer);
            res.header('Access-Control-Allow-Methods', 'GET,PUT,POST,DELETE');
            res.header('Access-Control-Allow-Headers', 'Content-Type');
            return next();
          };
        })(this));
      }
      this.app.route = (function(_this) {
        return function(source, target) {
          return _this.app.use(source, express["static"](target));
        };
      })(this);
      this.play(this.app, this.configMethods);
      this.app.use(require('errorhandler')({
        dumpExceptions: true,
        showStack: true
      }));
      this.app.server = http.createServer(this.app);
      port = this.app.get('port') || process.env.PORT || 8080;
      console.log("Express is listening on port " + port + "...");
      this.app.server.listen(port);
      return this.play(this.app, this.appMethods);
    };

    return Express;

  })(Recorder);
  return new Express();
});
