// Generated by CoffeeScript 1.6.3
(function() {
  define(['http', 'express', 'odo/config'], function(http, express, config) {
    return function(plugins) {
      var app, key, plugin, value, _i, _len, _ref,
        _this = this;
      app = express();
      plugins = plugins.map(function(plugin) {
        if (typeof plugin === 'function') {
          return new plugin;
        }
        return plugin;
      });
      _ref = config.express;
      for (key in _ref) {
        value = _ref[key];
        app.set(key, value);
      }
      app.configure(function() {
        var plugin, _i, _len;
        app.use(express.compress());
        app.use(express.urlencoded());
        app.use(express.json());
        app.use(express.methodOverride());
        app.use(express.cookieParser(app.get('cookie secret')));
        app.use(express.cookieSession({
          key: app.get('session key'),
          secret: app.get('session secret')
        }));
        app.modulepath = function(uri) {
          var items;
          items = uri.split('/');
          items.pop();
          return items.join('/');
        };
        app.route = function(source, target) {
          return app.use(source, express["static"](target));
        };
        for (_i = 0, _len = plugins.length; _i < _len; _i++) {
          plugin = plugins[_i];
          if (plugin.configure != null) {
            plugin.configure(app);
          }
        }
        app.use(app.router);
        return app.use(express.errorHandler({
          dumpExceptions: true,
          showStack: true
        }));
      });
      app.server = http.createServer(app);
      app.server.listen(process.env.PORT || 8080);
      for (_i = 0, _len = plugins.length; _i < _len; _i++) {
        plugin = plugins[_i];
        if (plugin.init != null) {
          plugin.init(app);
        }
      }
      return app;
    };
  });

}).call(this);
