// Generated by CoffeeScript 1.6.3
(function() {
  define(['redis'], function(redis) {
    var commandreceiver, commandsender, eventlistener, eventpublisher, handlers, listeners, result, subscriptions;
    commandsender = redis.createClient();
    eventpublisher = redis.createClient();
    subscriptions = [];
    listeners = {};
    handlers = {};
    result = {
      send: function(command) {
        console.log("" + command.command + " -> redis");
        command = JSON.stringify(command, null, 4);
        return commandsender.publish('commands', command);
      },
      handle: function(command, callback) {
        console.log(" -> " + command);
        if (handlers[command] != null) {
          console.log("Error, handler already set for " + command);
          return;
        }
        return handlers[command] = callback;
      },
      publish: function(event) {
        console.log("" + event.event + " -> redis");
        return eventpublisher.publish('events', JSON.stringify(event, null, 4));
      },
      receive: function(event, callback) {
        console.log(" -> " + event);
        if (listeners[event] == null) {
          listeners[event] = [];
        }
        return listeners[event].push(callback);
      },
      eventstream: function(callback) {
        console.log(" -> eventstream");
        return subscriptions.push(callback);
      }
    };
    commandreceiver = redis.createClient();
    commandreceiver.on('message', function(channel, command) {
      command = JSON.parse(command);
      if (handlers[command.command] != null) {
        console.log("" + command.command + " ->");
        return handlers[command.command](command);
      }
    });
    commandreceiver.subscribe('commands');
    eventlistener = redis.createClient();
    eventlistener.on('message', function(channel, event) {
      var listener, subscriber, _i, _j, _len, _len1, _ref, _results;
      event = JSON.parse(event);
      for (_i = 0, _len = subscriptions.length; _i < _len; _i++) {
        subscriber = subscriptions[_i];
        subscriber(event);
      }
      if (listeners[event.event] != null) {
        console.log("" + event.event + " ->");
        _ref = listeners[event.event];
        _results = [];
        for (_j = 0, _len1 = _ref.length; _j < _len1; _j++) {
          listener = _ref[_j];
          _results.push(listener(event));
        }
        return _results;
      }
    });
    eventlistener.subscribe('events');
    return result;
  });

}).call(this);
