// Generated by IcedCoffeeScript 1.6.3-g
(function() {
  var requirejs;



  requirejs = require('requirejs');

  requirejs.config({
    nodeRequire: require,
    paths: {
      service: './nodecqrs/service'
    }
  });

  requirejs(['odo/injectinto', 'odo/eventstore/eventdispatcher', 'nodecqrs/service/itemevents'], function(inject, dispatcher, itemevents) {
    var bindEvents;
    bindEvents = function(listener) {
      var method, name, _results;
      _results = [];
      for (name in listener) {
        method = listener[name];
        _results.push(inject.bind("eventlisteners:" + name, method));
      }
      return _results;
    };
    bindEvents(itemevents);
    dispatcher.start();
    return console.log('Starting denormaliser service');
  });

}).call(this);
