// Generated by IcedCoffeeScript 1.6.3-g
(function() {
  var requirejs;



  requirejs = require('requirejs');

  requirejs.config({
    nodeRequire: require,
    paths: {}
  });

  requirejs(['odo/express'], function(express) {
    var app;
    process.env.PORT = 3000;
    return app = express([requirejs('./odo/peek'), requirejs('./odo/handlebars'), requirejs('./nodecqrs/socket'), requirejs('./nodecqrs/routes')]);
  });

}).call(this);
