// Generated by IcedCoffeeScript 1.6.3-g
(function() {
  var requirejs;



  requirejs = require('requirejs');

  requirejs.config({
    nodeRequire: require,
    paths: {
      service: './nodecqrs/service'
    }
  });

  requirejs(['odo/injectinto', 'odo/hub', 'nodecqrs/service/itemevents'], function(inject, hub, itemevents) {
    var bindEvents;
    bindEvents = function(listener) {
      var method, name, _results;
      _results = [];
      for (name in listener) {
        method = listener[name];
        _results.push(hub.receive(name, method));
      }
      return _results;
    };
    return bindEvents(itemevents);
  });

}).call(this);
