// Generated by IcedCoffeeScript 1.6.3-g
(function() {
  var requirejs;



  requirejs = require('requirejs');

  requirejs.config({
    nodeRequire: require,
    paths: {
      domain: './nodecqrs/domain'
    }
  });

  requirejs(['odo/injectinto', 'nodecqrs/domain/itemcommands', 'odo/hub', 'odo/eventstore'], function(inject, itemcommands, hub, eventstore) {
    var bindCommands;
    bindCommands = function(handler) {
      var method, name, _results;
      _results = [];
      for (name in handler) {
        method = handler[name];
        _results.push(hub.handle(name, method));
      }
      return _results;
    };
    return bindCommands(itemcommands);
  });

}).call(this);
