// Generated by CoffeeScript 1.7.1
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  define([], function() {
    var Plugins;
    return Plugins = (function() {
      Plugins.prototype.contexts = ['web', 'domain', 'projection', 'api'];

      function Plugins(plugins) {
        this.context = __bind(this.context, this);
        var context, _i, _len, _ref;
        this.plugins = plugins;
        this.plugins = this.plugins.map(function(plugin) {
          if (typeof plugin === 'function') {
            return new plugin;
          }
          return plugin;
        });
        _ref = this.contexts;
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          context = _ref[_i];
          this[context] = this.context(context);
        }
      }

      Plugins.prototype.context = function(name) {
        return (function(_this) {
          return function() {
            var plugin, _i, _len, _ref, _results;
            _ref = _this.plugins;
            _results = [];
            for (_i = 0, _len = _ref.length; _i < _len; _i++) {
              plugin = _ref[_i];
              if (plugin[name] != null) {
                _results.push(plugin[name]());
              } else {
                _results.push(void 0);
              }
            }
            return _results;
          };
        })(this);
      };

      return Plugins;

    })();
  });

}).call(this);
