// Generated by CoffeeScript 1.7.1
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  define(['module', 'odo/express'], function(module, express) {
    var Public;
    return Public = (function() {
      function Public() {
        this.web = __bind(this.web, this);
      }

      Public.prototype.web = function() {
        return express.route('/', express.modulepath(module.uri) + '/../../public');
      };

      return Public;

    })();
  });

}).call(this);
