// Generated by CoffeeScript 1.8.0
define(['odo/config', 'redis'], function(config, redis) {
  return function() {
    if (config.redis.socket != null) {
      return redis.createClient(config.redis.socket);
    } else {
      return redis.createClient(config.redis.port, config.redis.host);
    }
  };
});
