// Generated by IcedCoffeeScript 1.6.3-g
(function() {
  var requirejs;



  requirejs = require('requirejs');

  requirejs.config({
    nodeRequire: require,
    paths: {
      service: './odo/eventstore/service'
    }
  });

  requirejs(['service/listener'], function(listener) {
    listener.start();
    return console.log('Starting service');
  });

}).call(this);
