// Generated by IcedCoffeeScript 1.6.3-g
(function() {
  var iced, requirejs, __iced_k, __iced_k_noop;

  iced = require('iced-coffee-script').iced;
  __iced_k = __iced_k_noop = function() {};

  requirejs = require('requirejs');

  requirejs.config({
    nodeRequire: require,
    paths: {}
  });

  requirejs(['module', 'express', 'path', 'fs', 'peekinto', 'odo/plugins', 'odo/config'], function(module, express, path, fs, peek, plugins, config) {
    var app, key, value, ___iced_passed_deferral, __iced_deferrals, __iced_k,
      _this = this;
    __iced_k = __iced_k_noop;
    ___iced_passed_deferral = iced.findDeferral(arguments);
    app = express();
    (function(__iced_k) {
      __iced_deferrals = new iced.Deferrals(__iced_k, {
        parent: ___iced_passed_deferral,
        filename: "/Users/tcoats/Source/odo/thomascoats.com.coffee"
      });
      plugins.loadplugins(['', 'odo'], __iced_deferrals.defer({
        lineno: 16
      }));
      __iced_deferrals._fulfill();
    })(function() {
      var _ref;
      _ref = config.express;
      for (key in _ref) {
        value = _ref[key];
        app.set(key, value);
      }
      app.configure(function() {
        var ___iced_passed_deferral1, __iced_deferrals, __iced_k;
        __iced_k = __iced_k_noop;
        ___iced_passed_deferral1 = iced.findDeferral(arguments);
        app.use(express.compress());
        app.use(express.bodyParser());
        app.use(express.methodOverride());
        app.use(express.cookieParser(app.get('cookie secret')));
        app.use(express.cookieSession({
          key: app.get('session key'),
          secret: app.get('session secret')
        }));
        app.use('/', express["static"](path.dirname(module.uri) + '/thomascoats.com/public'));
        peek(app);
        (function(__iced_k) {
          __iced_deferrals = new iced.Deferrals(__iced_k, {
            parent: ___iced_passed_deferral1,
            filename: "/Users/tcoats/Source/odo/thomascoats.com.coffee"
          });
          plugins.configure(app, __iced_deferrals.defer({
            lineno: 41
          }));
          __iced_deferrals._fulfill();
        })(function() {
          app.use(app.router);
          return app.use(express.errorHandler({
            dumpExceptions: true,
            showStack: true
          }));
        });
      });
      app.listen(process.env.PORT || 80);
      __iced_deferrals = new iced.Deferrals(__iced_k, {
        parent: ___iced_passed_deferral,
        filename: "/Users/tcoats/Source/odo/thomascoats.com.coffee"
      });
      plugins.init(app, __iced_deferrals.defer({
        lineno: 53
      }));
      __iced_deferrals._fulfill();
    });
  });

}).call(this);
