// Generated by CoffeeScript 1.6.3
(function() {
  var requirejs;

  requirejs = require('requirejs');

  requirejs.config({
    nodeRequire: require,
    paths: {}
  });

  requirejs(['odo/express'], function(express) {
    var app;
    process.env.PORT = 80;
    return app = express([requirejs('./odo/plugins/peek'), requirejs('./odo/plugins/bower'), requirejs('./odo/plugins/durandal'), requirejs('./odo/plugins/handlebars'), requirejs('./odo/plugins/twitterauth'), requirejs('./thomascoats.com/plugins/public'), requirejs('./thomascoats.com/plugins/article')]);
  });

}).call(this);
