// Generated by CoffeeScript 1.6.3
(function() {
  var requirejs;

  requirejs = require('requirejs');

  requirejs.config({
    nodeRequire: require,
    paths: {}
  });

  requirejs(['odo/express'], function(express) {
    var app;
    process.env.PORT = 80;
    return app = express([requirejs('./odo/peek'), requirejs('./odo/bower'), requirejs('./odo/durandal'), requirejs('./odo/handlebars'), requirejs('./odo/twitterauth'), requirejs('./thomascoats.com/routes'), requirejs('./thomascoats.com/articleroutes')]);
  });

}).call(this);
