// Generated by IcedCoffeeScript 1.6.3-g
(function() {


  define(['odo/hubjs'], function(hub) {
    return {
      configure: function(app) {
        return app.hub = hub;
      }
    };
  });

}).call(this);
