// Generated by IcedCoffeeScript 1.4.0c
(function() {

  $(function() {
    var $filter, $page, $pagelinks, $pages;
    $filter = $('.pagefilter');
    $pages = _($('.pagemenu li:not(.nav-header)')).map(function(el) {
      return {
        $el: $(el),
        text: $(el).find('a').text()
      };
    });
    $filter.keyup(function() {
      var val;
      val = $filter.val();
      return _($pages).each(function(page) {
        if ((val == null) || page.text.caseInsensitiveContains(val)) {
          return page.$el.show();
        } else {
          return page.$el.hide();
        }
      });
    });
    $pagelinks = $('.pagemenu a');
    $page = $('.page');
    return $pagelinks.click(function(e) {
      var $this;
      e.preventDefault();
      $this = $(this);
      return $.get($this.attr('href'), function(data) {
        return $page.html((new Showdown.converter()).makeHtml(data.contents));
      });
    });
  });

}).call(this);
