// Generated by CoffeeScript 1.6.3
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  define([], function() {
    var Recorder;
    return Recorder = (function() {
      Recorder.prototype._calls = [];

      Recorder.prototype._record = function(method) {
        var _this = this;
        return function() {
          return _this._calls.push({
            method: method,
            params: Array.prototype.slice.call(arguments, 0)
          });
        };
      };

      function Recorder(methods) {
        this.play = __bind(this.play, this);
        this._record = __bind(this._record, this);
        var method, _i, _len;
        for (_i = 0, _len = methods.length; _i < _len; _i++) {
          method = methods[_i];
          this[method] = this._record(method);
        }
      }

      Recorder.prototype.play = function(target) {
        var call, _i, _len, _ref, _results;
        _ref = this._calls;
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          call = _ref[_i];
          _results.push(target[call.method].apply(target, call.params));
        }
        return _results;
      };

      return Recorder;

    })();
  });

}).call(this);
