// Generated by CoffeeScript 1.7.1
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  define(['passport', 'passport-oauth2', 'odo/config', 'odo/messaging/hub', 'node-uuid', 'redis', 'odo/express/app'], function(passport, passportoauth2, config, hub, uuid, redis, app) {
    var OAuth2Authentication, db;
    db = redis.createClient();
    return OAuth2Authentication = (function() {
      function OAuth2Authentication() {
        this.signin = __bind(this.signin, this);
        this.projection = __bind(this.projection, this);
        this.web = __bind(this.web, this);
      }

      OAuth2Authentication.prototype.web = function() {
        passport.use(new passportoauth2.Strategy({
          clientID: config.passport.oauth2['client id'],
          clientSecret: config.passport.oauth2['client secret'],
          callbackURL: config.passport.oauth2['host'] + 'odo/auth/oauth2/callback',
          authorizationURL: config.passport.oauth2['authorization url'],
          tokenURL: config.passport.oauth2['token url']
        }, function(accessToken, refreshToken, profile, done) {
          console.log('Found profile!');
          console.log(profile);
          return process.nextTick(function() {
            return done(null, profile);
          });
        }));
        app.get('/odo/auth/oauth2', passport.authenticate('oauth2'));
        return app.get('/odo/auth/oauth2/callback', function(req, res, next) {
          return passport.authenticate('oauth2', function(err, user, info) {
            var _ref, _ref1;
            if (err != null) {
              return next(err);
            }
            if (!user) {
              if (((_ref = config.odo.auth) != null ? (_ref1 = _ref.oauth2) != null ? _ref1.failureRedirect : void 0 : void 0) != null) {
                return res.redirect(config.odo.auth.oauth2.failureRedirect);
              }
              return res.redirect('/#auth/oauth2/failure');
            }
            return req.logIn(user, function(err) {
              var returnTo, _ref2, _ref3, _ref4;
              if (err != null) {
                return next(err);
              }
              if (((_ref2 = req.session) != null ? _ref2.returnTo : void 0) != null) {
                returnTo = req.session.returnTo;
                delete req.session.returnTo;
                return res.redirect(returnTo);
              }
              if (((_ref3 = config.odo.auth) != null ? (_ref4 = _ref3.oauth2) != null ? _ref4.successRedirect : void 0 : void 0) != null) {
                return res.redirect(config.odo.auth.oauth2.successRedirect);
              }
              return res.redirect('/#auth/oauth2/success');
            });
          })(req, res, next);
        });
      };

      OAuth2Authentication.prototype.projection = function() {
        hub.receive('userOAuth2Connected', (function(_this) {
          return function(event, cb) {
            return db.hset("" + config.odo.domain + ":useroauth2", event.payload.profile.id, event.payload.id, function() {
              return cb();
            });
          };
        })(this));
        return hub.receive('userOAuth2Disconnected', (function(_this) {
          return function(event, cb) {
            return db.hdel("" + config.odo.domain + ":useroauth2", event.payload.profile.id, function() {
              return cb();
            });
          };
        })(this));
      };

      OAuth2Authentication.prototype.signin = function(req, accessToken, refreshToken, profile, done) {
        var userid;
        userid = null;
        return this.get(profile.id, (function(_this) {
          return function(err, userid) {
            var user;
            if (err != null) {
              done(err);
              return;
            }
            if ((req.user != null) && (userid != null) && req.user.id !== userid) {
              done(null, false, {
                message: 'This OAuth2 account is connected to another Blackbeard account'
              });
              return;
            }
            if (req.user != null) {
              console.log('user already exists, connecting OAuth2 to user');
              userid = req.user.id;
              hub.send({
                command: 'connectOAuth2ToUser',
                payload: {
                  id: userid,
                  profile: profile
                }
              });
            } else if (userid == null) {
              console.log('no user exists yet, creating a new id');
              userid = uuid.v1();
              hub.send({
                command: 'startTrackingUser',
                payload: {
                  id: userid,
                  profile: profile
                }
              });
              hub.send({
                command: 'connectOAuth2ToUser',
                payload: {
                  id: userid,
                  profile: profile
                }
              });
              hub.send({
                command: 'assignDisplayNameToUser',
                payload: {
                  id: userid,
                  displayName: profile.displayName
                }
              });
            } else {
              hub.send({
                command: 'connectOAuth2ToUser',
                payload: {
                  id: userid,
                  profile: profile
                }
              });
            }
            user = {
              id: userid,
              profile: profile
            };
            return done(null, user);
          };
        })(this));
      };

      OAuth2Authentication.prototype.get = function(id, callback) {
        return db.hget("" + config.odo.domain + ":useroauth2", id, (function(_this) {
          return function(err, data) {
            if (err != null) {
              callback(err);
              return;
            }
            if (data != null) {
              callback(null, data);
              return;
            }
            return db.hget("" + config.odo.domain + ":useroauth2", id, function(err, data) {
              if (err != null) {
                callback(err);
                return;
              }
              return callback(null, data);
            });
          };
        })(this));
      };

      return OAuth2Authentication;

    })();
  });

}).call(this);
