// Generated by CoffeeScript 1.6.3
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  define(['redis', 'odo/config'], function(redis, config) {
    var UserProfile, db;
    db = redis.createClient();
    return UserProfile = (function() {
      function UserProfile() {
        this.addOrRemoveValues = __bind(this.addOrRemoveValues, this);
        var _this = this;
        this.receive = {
          userTrackingStarted: function(event) {
            var user;
            user = {
              id: event.payload.id,
              displayName: event.payload.profile.displayName
            };
            return db.hset("" + config.odo.domain + ":users", event.payload.id, JSON.stringify(user));
          },
          userHasEmailAddress: function(event) {
            return _this.addOrRemoveValues(event, function(user) {
              user.email = event.payload.email;
              return user;
            });
          },
          userHasDisplayName: function(event) {
            return _this.addOrRemoveValues(event, function(user) {
              user.displayName = event.payload.displayName;
              return user;
            });
          },
          userHasUsername: function(event) {
            return _this.addOrRemoveValues(event, function(user) {
              user.username = event.payload.username;
              return user;
            });
          },
          userTwitterAttached: function(event) {
            return _this.addOrRemoveValues(event, function(user) {
              user.twitter = {
                id: event.payload.profile.id,
                profile: event.payload.profile
              };
              return user;
            });
          },
          userFacebookAttached: function(event) {
            return _this.addOrRemoveValues(event, function(user) {
              user.facebook = {
                id: event.payload.profile.id,
                profile: event.payload.profile
              };
              return user;
            });
          },
          userGoogleAttached: function(event) {
            return _this.addOrRemoveValues(event, function(user) {
              user.google = {
                id: event.payload.profile.id,
                profile: event.payload.profile
              };
              return user;
            });
          },
          userHasLocalSignin: function(event) {
            return _this.addOrRemoveValues(event, function(user) {
              user.local = {
                id: event.payload.id,
                profile: event.payload.profile
              };
              return user;
            });
          }
        };
      }

      UserProfile.prototype.addOrRemoveValues = function(event, callback) {
        var _this = this;
        return db.hget("" + config.odo.domain + ":users", event.payload.id, function(err, user) {
          if (err != null) {
            return;
          }
          user = JSON.parse(user);
          user = callback(user);
          user = JSON.stringify(user);
          return db.hset("" + config.odo.domain + ":users", event.payload.id, user);
        });
      };

      UserProfile.prototype.get = function(id, callback) {
        var _this = this;
        return db.hget("" + config.odo.domain + ":users", id, function(err, data) {
          if (err != null) {
            callback(err);
            return;
          }
          data = JSON.parse(data);
          if (data != null) {
            callback(null, data);
            return;
          }
          return setTimeout(function() {
            return db.hget("" + config.odo.domain + ":users", id, function(err, data) {
              if (err != null) {
                callback(err);
                return;
              }
              data = JSON.parse(data);
              return callback(null, data);
            });
          }, 1000);
        });
      };

      return UserProfile;

    })();
  });

}).call(this);
