// Generated by CoffeeScript 1.6.3
(function() {
  define(['redis', 'odo/config'], function(redis, config) {
    var UserProfile, db;
    db = redis.createClient();
    return UserProfile = (function() {
      function UserProfile() {
        var _this = this;
        this.receive = {
          userTrackingStarted: function(event) {
            var user;
            user = {
              id: event.payload.id,
              profile: event.payload.profile
            };
            return db.hset("" + config.odo.domain + ":users", event.payload.id, JSON.stringify(user));
          },
          userTwitterAttached: function(event) {
            var user;
            user = {
              id: event.payload.id,
              profile: event.payload.profile
            };
            return db.hset("" + config.odo.domain + ":users", event.payload.id, JSON.stringify(user));
          },
          userHasLocalSignin: function(event) {
            return db.hget("" + config.odo.domain + ":users", event.payload.id, function(err, user) {
              if (err != null) {
                return;
              }
              user = JSON.parse(user);
              user.profile.username = event.payload.profile.username;
              user.profile.password = event.payload.profile.password;
              user = JSON.stringify(user);
              return db.hset("" + config.odo.domain + ":users", event.payload.id, user);
            });
          }
        };
      }

      UserProfile.prototype.get = function(id, callback) {
        var _this = this;
        return db.hget("" + config.odo.domain + ":users", id, function(err, data) {
          if (err != null) {
            callback(err);
            return;
          }
          data = JSON.parse(data);
          if (data != null) {
            callback(null, data);
            return;
          }
          return setTimeout(function() {
            return db.hget("" + config.odo.domain + ":users", id, function(err, data) {
              if (err != null) {
                callback(err);
                return;
              }
              data = JSON.parse(data);
              return callback(null, data);
            });
          }, 1000);
        });
      };

      return UserProfile;

    })();
  });

}).call(this);
