// Generated by CoffeeScript 1.7.1
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  define(['restify', 'odo/config', 'odo/restify/configure', 'odo/restify/app'], function(restify, config, _configure, _app) {
    var Restify;
    return Restify = (function() {
      function Restify() {
        this.api = __bind(this.api, this);
      }

      Restify.prototype.api = function() {
        var port, _ref;
        this.server = restify.createServer();
        _configure.play(this.server);
        _app.play(this.server);
        port = ((_ref = config.restify) != null ? _ref.port : void 0) || process.env.PORT || 8080;
        return this.server.listen(port, function() {
          return console.log("Restify listening on port " + port + "...");
        });
      };

      return Restify;

    })();
  });

}).call(this);
