// Generated by CoffeeScript 1.6.3
(function() {
  define(['jquery'], function($) {
    var _this = this;
    return {
      getUsernameAvailability: function(username) {
        return $.get('/odo/auth/local/usernameavailability', {
          username: username
        });
      },
      testAuthentication: function(username, password) {
        return $.get('/odo/auth/local/test', {
          username: username,
          password: password
        });
      },
      assignPasswordToUser: function(id, password) {
        return $.post('/sendcommand/assignPasswordToUser', {
          id: id,
          password: password
        });
      }
    };
  });

}).call(this);
