// Generated by IcedCoffeeScript 1.6.3-g
(function() {
  var requirejs;



  requirejs = require('requirejs');

  requirejs.config({
    nodeRequire: require,
    paths: {}
  });

  requirejs(['handler'], function(handler) {
    handler.start();
    return console.log('Starting domain service');
  });

}).call(this);
