// Generated by IcedCoffeeScript 1.6.3-g
(function() {


  define(['node-uuid', 'item'], function(uuid, Item) {
    return {
      createItem: function(command, context) {
        var id, item, newId;
        id = uuid.v1();
        newId = "item:" + id;
        console.log("create a new aggregate with id= " + newId);
        item = new Item(newId);
        return context.applyHistoryThenCommand(item);
      },
      deleteItem: function(command, context) {
        var item;
        item = new Item(command.id);
        return context.applyHistoryThenCommand(item);
      },
      changeItem: function(command, context) {
        var item;
        item = new Item(command.id);
        return context.applyHistoryThenCommand(item);
      }
    };
  });

}).call(this);
