// Generated by IcedCoffeeScript 1.6.3-g
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };



  define(['knockout', 'durandal/system', 'plugins/dialog'], function(ko, system, dialog) {
    var Dialog;
    return Dialog = (function() {
      function Dialog(options) {
        this.shake = __bind(this.shake, this);
        this.close = __bind(this.close, this);
        this.show = __bind(this.show, this);
        var activationData;
        activationData = {
          dialog: this
        };
        system.extend(activationData, options.activationData);
        this.composeOptions = ko.observable({
          model: options.model,
          activationData: activationData
        });
        this.shouldShake = ko.observable(false);
      }

      Dialog.prototype.show = function() {
        return dialog.show(this);
      };

      Dialog.prototype.close = function(response) {
        return dialog.close(this, response);
      };

      Dialog.prototype.shake = function() {
        var _this = this;
        this.shouldShake(true);
        return setTimeout(function() {
          return _this.shouldShake(false);
        }, 1000);
      };

      return Dialog;

    })();
  });

}).call(this);
