// Generated by IcedCoffeeScript 1.6.3-g
(function() {


  define(['module', 'path', 'express'], function(module, path, express) {
    return {
      configure: function(app) {
        return app.use('/odo/durandal', express["static"](path.dirname(module.uri) + '/durandal-public'));
      }
    };
  });

}).call(this);
