// Generated by IcedCoffeeScript 1.6.3-g
(function() {


  define(['odo/hub', 'odo/injectinto'], function(hub, inject) {
    return {
      start: function() {
        return hub.on('events', function(data) {
          var listener, _i, _len, _ref, _results;
          console.log(data);
          console.log("eventDenormalizer -- denormalize event " + data.event);
          _ref = inject.many("eventlisteners:" + data.event);
          _results = [];
          for (_i = 0, _len = _ref.length; _i < _len; _i++) {
            listener = _ref[_i];
            _results.push(listener(data));
          }
          return _results;
        });
      }
    };
  });

}).call(this);
