// Generated by IcedCoffeeScript 1.6.3-g
(function() {


  define(['eventstore', 'eventstore.redis', 'odo/hub'], function(eventstore, storage, hub) {
    var es;
    es = eventstore.createStore();
    es.configure(function() {
      es.use({
        publish: hub.publish
      });
      return es.use(storage.createStorage());
    }).start();
    return {
      applyHistoryThenCommand: function(aggregate, command) {
        return es.getEventStream(aggregate.id, function(err, stream) {
          console.log("applying " + stream.events.length + " events to " + aggregate.id);
          aggregate.loadFromHistory(stream.events);
          console.log("applying " + command.command);
          return aggregate[command.command](command.payload, function(err, uncommitted) {
            var event, _i, _len;
            if (err) {
              console.log(err);
              return;
            }
            for (_i = 0, _len = uncommitted.length; _i < _len; _i++) {
              event = uncommitted[_i];
              stream.addEvent(event);
            }
            return stream.commit();
          });
        });
      }
    };
  });

}).call(this);
