// Generated by IcedCoffeeScript 1.6.3-g
(function() {


  define(['peekinto'], function(peek) {
    return {
      configure: function(app) {
        return peek(app);
      }
    };
  });

}).call(this);
