// Generated by IcedCoffeeScript 1.6.3-g
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };



  define(['node-uuid'], function(uuid) {
    var Item;
    return Item = (function() {
      function Item(id) {
        this.loadFromHistory = __bind(this.loadFromHistory, this);
        this.apply = __bind(this.apply, this);
        this["new"] = __bind(this["new"], this);
        this._itemDeleted = __bind(this._itemDeleted, this);
        this._itemChanged = __bind(this._itemChanged, this);
        this._itemCreated = __bind(this._itemCreated, this);
        this.deleteItem = __bind(this.deleteItem, this);
        this.changeItem = __bind(this.changeItem, this);
        this.createItem = __bind(this.createItem, this);
        this.id = id;
        this.text = '';
        this._destroy = false;
        this.uncommittedEvents = [];
        this;
      }

      Item.prototype.createItem = function(command, callback) {
        if (command.text === '') {
          callback(new Error('It is not allowed to set an item text to empty string.'));
          return;
        }
        this["new"]('itemCreated', {
          id: this.id,
          text: command.text
        });
        return callback(null, this.uncommittedEvents);
      };

      Item.prototype.changeItem = function(command, callback) {
        if (command.text === '') {
          callback(new Error('It is not allowed to set an item text to empty string.'));
          return;
        }
        this["new"]('itemChanged', {
          id: this.id,
          text: command.text
        });
        return callback(null, this.uncommittedEvents);
      };

      Item.prototype.deleteItem = function(command, callback) {
        this["new"]('itemDeleted', {
          id: this.id,
          text: this.text
        });
        return callback(null, this.uncommittedEvents);
      };

      Item.prototype._itemCreated = function(event) {
        return this.text = event.payload.text;
      };

      Item.prototype._itemChanged = function(event) {
        return this.text = event.payload.text;
      };

      Item.prototype._itemDeleted = function(event) {
        return this._destroy = true;
      };

      Item.prototype["new"] = function(event, payload) {
        return this.apply({
          id: uuid.v1(),
          time: new Date(),
          payload: payload,
          event: event
        });
      };

      Item.prototype.apply = function(event) {
        this["_" + event.event](event);
        if (!event.fromHistory) {
          return this.uncommittedEvents.push(event);
        }
      };

      Item.prototype.loadFromHistory = function(history) {
        var event, _i, _len, _results;
        _results = [];
        for (_i = 0, _len = history.length; _i < _len; _i++) {
          event = history[_i];
          event.payload.fromHistory = true;
          _results.push(this.apply(event.payload));
        }
        return _results;
      };

      return Item;

    })();
  });

}).call(this);
