// Generated by IcedCoffeeScript 1.6.3-g
(function() {


  define(['node-uuid', 'nodecqrs/domain/item'], function(uuid, Item) {
    return {
      createItem: function(command, context) {
        var id, item, newId;
        id = uuid.v1();
        newId = "item:" + id;
        item = new Item(newId);
        return context.applyHistoryThenCommand(item, command);
      },
      deleteItem: function(command, context) {
        var item;
        item = new Item(command.payload.id);
        return context.applyHistoryThenCommand(item, command);
      },
      changeItem: function(command, context) {
        var item;
        item = new Item(command.payload.id);
        return context.applyHistoryThenCommand(item, command);
      }
    };
  });

}).call(this);
