// Generated by IcedCoffeeScript 1.6.3-g
(function() {


  define(['odo/eventstore', 'node-uuid', 'nodecqrs/domain/item'], function(es, uuid, Item) {
    return {
      createItem: function(command) {
        var id, item, newId;
        id = uuid.v1();
        newId = "item:" + id;
        item = new Item(newId);
        es.extend(item);
        return item.applyHistoryThenCommand(command);
      },
      deleteItem: function(command) {
        var item;
        item = new Item(command.payload.id);
        es.extend(item);
        return item.applyHistoryThenCommand(command);
      },
      changeItem: function(command) {
        var item;
        item = new Item(command.payload.id);
        es.extend(item);
        return item.applyHistoryThenCommand(command);
      }
    };
  });

}).call(this);
