// Generated by IcedCoffeeScript 1.4.0a
(function() {

  $(function() {
    return $('#admin-plugin input').change(function(e) {
      var $input, $label, checked, id;
      $input = $(this);
      $label = $input.parent('label');
      id = $input.attr('name');
      checked = $input.prop('checked');
      $label.toggleClass('plugin-disabled', !checked);
      return $.post(id + '/', {
        disabled: !checked
      });
    });
  });

}).call(this);
