// Generated by CoffeeScript 1.6.3
(function() {
  define(['module', 'passport', 'odo/projections/userprofile'], function(module, passport, UserProfile) {
    return {
      configure: function(app) {
        app.route('/odo', app.modulepath(module.uri) + '/auth-public');
        app.use(passport.initialize());
        app.use(passport.session());
        passport.serializeUser(function(user, done) {
          return done(null, user.id);
        });
        return passport.deserializeUser(function(id, done) {
          return new UserProfile().get(id, done);
        });
      },
      init: function(app) {
        app.get('/auth/signout', function(req, res) {
          req.logout();
          return res.redirect('/');
        });
        return app.get('/auth/user', function(req, res) {
          if (req.user == null) {
            res.send(403, 'authentication required');
            return;
          }
          return res.send(req.user);
        });
      }
    };
  });

}).call(this);
