// Generated by CoffeeScript 1.6.3
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  define(['module'], function(module) {
    var Plugin;
    return Plugin = (function() {
      function Plugin() {
        this.handle = __bind(this.handle, this);
        this.receive = __bind(this.receive, this);
        this.init = __bind(this.init, this);
        this.configure = __bind(this.configure, this);
      }

      Plugin.prototype.configure = function(app) {
        return app.route('/', app.modulepath(module.uri) + '/plugin-public');
      };

      Plugin.prototype.init = function(app) {
        var _this = this;
        return app.get('/test', function(req, res) {
          return res.send('Passed');
        });
      };

      Plugin.prototype.receive = function(hub) {
        var _this = this;
        return hub.receive('testEvent', function(event, cb) {
          console.log('Test Event Received');
          return cb();
        });
      };

      Plugin.prototype.handle = function(hub) {
        var _this = this;
        return hub.handle('testCommand', function(command) {
          return console.log('Test Command Received');
        });
      };

      return Plugin;

    })();
  });

}).call(this);
