// Generated by CoffeeScript 1.6.3
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  define(['module'], function(module) {
    var ExamplePlugin;
    return ExamplePlugin = (function() {
      function ExamplePlugin() {
        this.handle = __bind(this.handle, this);
        this.receive = __bind(this.receive, this);
        this.init = __bind(this.init, this);
        this.configure = __bind(this.configure, this);
      }

      ExamplePlugin.prototype.configure = function(app) {
        app.route('/', app.modulepath(module.uri) + '/example-public');
        return app.durandal('views/example');
      };

      ExamplePlugin.prototype.init = function(app) {
        var _this = this;
        return app.get('/example', function(req, res) {
          return res.send('Passed');
        });
      };

      ExamplePlugin.prototype.receive = function(hub) {
        var _this = this;
        return hub.receive('exampleEvent', function(event, cb) {
          console.log('example Event Received');
          return cb();
        });
      };

      ExamplePlugin.prototype.handle = function(hub) {
        var _this = this;
        return hub.handle('exampleCommand', function(command) {
          return console.log('example Command Received');
        });
      };

      return ExamplePlugin;

    })();
  });

}).call(this);
