// Generated by IcedCoffeeScript 1.6.3-g
(function() {


  define(['nodecqrs/storage'], function(store) {
    return {
      init: function(app) {
        app.get('/', function(req, res) {
          return res.render({
            view: 'nodecqrs/layout',
            data: {
              title: 'nodecqrs example'
            },
            partials: {
              content: 'index'
            }
          });
        });
        return app.get('/allItems.json', function(req, res) {
          return store.loadAll(function(err, items) {
            if (err) {
              res.json({});
            }
            return res.json(items);
          });
        });
      }
    };
  });

}).call(this);
