// Generated by IcedCoffeeScript 1.6.3-g
(function() {


  define(['socket.io', 'odo/hub'], function(socket, hub) {
    return {
      init: function(app) {
        app.io = socket.listen(app.server);
        app.io.sockets.on('connection', function(socket) {
          var conn;
          conn = "" + socket.handshake.address.address + ":" + socket.handshake.address.port;
          console.log("" + conn + " -- connects to socket.io");
          return socket.on('commands', function(data) {
            console.log("" + conn + " -- sending command " + data.command);
            return hub.send(data.command, conn, data);
          });
        });
        return hub.on('events', function(data) {
          console.log("socket.io -- publish event " + data.event + " to browser");
          return app.io.sockets.emit('events', data);
        });
      }
    };
  });

}).call(this);
