// Generated by CoffeeScript 1.6.3
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  define([], function() {
    var User;
    return User = (function() {
      function User(id) {
        this._userTwitterAttached = __bind(this._userTwitterAttached, this);
        this._userTrackingStarted = __bind(this._userTrackingStarted, this);
        this.attachTwitterToUser = __bind(this.attachTwitterToUser, this);
        this.startTrackingUser = __bind(this.startTrackingUser, this);
        this.id = id;
      }

      User.prototype.startTrackingUser = function(command, callback) {
        this["new"]('userTrackingStarted', {
          id: this.id,
          profile: command.profile
        });
        return callback(null);
      };

      User.prototype.attachTwitterToUser = function(command, callback) {
        this["new"]('userTwitterAttached', {
          id: this.id,
          profile: command.profile
        });
        return callback(null);
      };

      User.prototype._userTrackingStarted = function(event) {};

      User.prototype._userTwitterAttached = function(event) {};

      return User;

    })();
  });

}).call(this);
