// Generated by CoffeeScript 1.6.3
(function() {
  define(['odo/eventstore', 'odo/domain/user'], function(es, User) {
    var defaultHandler;
    defaultHandler = function(command) {
      var user;
      user = new User(command.payload.id);
      es.extend(user);
      return user.applyHistoryThenCommand(command);
    };
    return {
      startTrackingUser: defaultHandler,
      assignEmailAddressToUser: defaultHandler,
      assignDisplayNameToUser: defaultHandler,
      assignUsernameToUser: defaultHandler,
      connectTwitterToUser: defaultHandler,
      disconnectTwitterFromUser: defaultHandler,
      connectFacebookToUser: defaultHandler,
      disconnectFacebookFromUser: defaultHandler,
      connectGoogleToUser: defaultHandler,
      disconnectGoogleFromUser: defaultHandler,
      createLocalSigninForUser: defaultHandler,
      assignPasswordToUser: defaultHandler,
      removeLocalSigninForUser: defaultHandler
    };
  });

}).call(this);
