// Generated by CoffeeScript 1.6.3
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  define([], function() {
    var Item;
    return Item = (function() {
      function Item(id) {
        this._articleDeleted = __bind(this._articleDeleted, this);
        this._contentUpdated = __bind(this._contentUpdated, this);
        this._articleCreated = __bind(this._articleCreated, this);
        this.deleteArticle = __bind(this.deleteArticle, this);
        this.updateArticleContent = __bind(this.updateArticleContent, this);
        this.createArticle = __bind(this.createArticle, this);
        this.id = id;
        this._destroy = false;
        this.name = '';
        this.title = '';
        this.content = '';
      }

      Item.prototype.createArticle = function(command, callback) {
        if ((command.name == null) || command.name === '') {
          callback(new Error('Article name needed'));
          return;
        }
        this["new"]('articleCreated', {
          id: this.id,
          name: command.name
        });
        return callback(null);
      };

      Item.prototype.updateArticleContent = function(command, callback) {
        if ((command.content == null) === '') {
          callback(new Error('Article content needed'));
          return;
        }
        this["new"]('contentUpdated', {
          id: this.id,
          content: command.content
        });
        return callback(null);
      };

      Item.prototype.deleteArticle = function(command, callback) {
        this["new"]('articleDeleted', {
          id: this.id
        });
        return callback(null);
      };

      Item.prototype._articleCreated = function(event) {
        return this.name = event.name;
      };

      Item.prototype._contentUpdated = function(event) {
        return this.content = event.content;
      };

      Item.prototype._articleDeleted = function(event) {
        return this._destroy = true;
      };

      return Item;

    })();
  });

}).call(this);
