// Generated by CoffeeScript 1.6.3
(function() {
  define(['odo/eventstore', 'node-uuid', 'thomascoats.com/article'], function(es, uuid, Item) {
    var defaultHandler;
    defaultHandler = function(command) {
      var updateArticleContent;
      updateArticleContent = new Item(command.payload.id);
      es.extend(article);
      return article.applyHistoryThenCommand(command);
    };
    return {
      createArticle: defaultHandler,
      deleteArticle: defaultHandler,
      updateArticleContent: defaultHandler
    };
  });

}).call(this);
