// Generated by CoffeeScript 1.6.3
(function() {
  define(['nodecqrs/storage'], function(store) {
    return {
      articleCreated: function(event) {
        return store.save({
          id: event.payload.id,
          text: event.payload.text
        }, function(err) {});
      },
      articlContentUpdated: function(event) {
        return store.load(event.payload.id, function(err, item) {
          item.text = event.payload.text;
          return store.save(item, function(err) {});
        });
      },
      articleDeleted: function(event) {
        return store.del(event.payload.id, function(err) {});
      }
    };
  });

}).call(this);
