// Generated by CoffeeScript 1.6.3
(function() {
  define(['redis'], function(redis) {
    var db;
    db = redis.createClient();
    return {
      receive: {
        articleCreated: function(event) {
          var article;
          article = {
            id: event.payload.id,
            name: event.payload.name
          };
          return db.set("articlecontent:" + article.id, JSON.stringify(article));
        },
        articleContentUpdated: function(event) {
          var article;
          article = {
            id: event.payload.id,
            content: event.payload.content
          };
          return db.get("articlecontent:" + article.id, function(err, data) {
            if (err != null) {
              console.log(err);
              return;
            }
            data = JSON.parse(data);
            article.name = data.name;
            return db.set("articlecontent:" + article.id, JSON.stringify(article));
          });
        },
        articleDeleted: function(event) {
          var article;
          article = {
            id: event.payload.id
          };
          return db.del("articlecontent:" + article.id);
        }
      },
      get: function(id, callback) {
        return db.get("articlecontent:" + id, function(err, data) {
          if (err != null) {
            callback(err);
            return;
          }
          data = JSON.parse(data);
          return callback(null, data);
        });
      }
    };
  });

}).call(this);
