// Generated by CoffeeScript 1.6.3
(function() {
  define(['redis'], function(redis) {
    var db;
    db = redis.createClient();
    return {
      receive: {
        articleCreated: function(event) {
          var id, name, userid;
          userid = event.payload.by;
          id = event.payload.id;
          name = event.payload.name;
          return db.hset("ownedarticles:" + userid, id, name);
        },
        articleDeleted: function(event) {
          var id, userid;
          userid = event.payload.by;
          id = event.payload.id;
          return db.hdel("ownedarticles:" + userid, id);
        }
      },
      get: function(userid, callback) {
        return db.hgetall("ownedarticles:" + userid, function(err, articles) {
          if (err != null) {
            callback(err);
            return;
          }
          return callback(null, articles);
        });
      }
    };
  });

}).call(this);
