// Generated by CoffeeScript 1.6.3
(function() {
  define(['redis'], function(redis) {
    var db;
    db = redis.createClient();
    return {
      receive: {
        articleCreated: function(event) {
          var articleid, userid;
          userid = event.payload.by;
          articleid = event.payload.id;
          return db.sadd("ownedarticles:" + userid, articleid);
        },
        articleDeleted: function(event) {
          var articleid, userid;
          userid = event.payload.by;
          articleid = event.payload.id;
          return db.srem("ownedarticles:" + userid, articleid);
        }
      },
      get: function(userid, callback) {
        return db.smembers("ownedarticles:" + userid, function(err, articles) {
          if (err != null) {
            callback(err);
            return;
          }
          return callback(null, articles);
        });
      }
    };
  });

}).call(this);
