// Generated by IcedCoffeeScript 1.4.0c
(function() {
  var express, _;

  express = require('express');

  _ = require('underscore');

  module.exports = {
    configure: function(app) {
      return app.use('/img', express["static"](__dirname + '/img'));
    },
    init: function(app) {
      return app.get('/', function(req, res) {
        return res.render({
          view: 'odo/layout',
          data: {
            title: 'Display',
            user: req.user,
            bodyclasses: ['lead']
          },
          partials: {
            content: 'display/display'
          }
        });
      });
    }
  };

}).call(this);
