// Generated by IcedCoffeeScript 1.4.0a
(function() {
  var _;

  _ = require('underscore');

  module.exports = {
    init: function(app) {
      var load;
      load = function(req, res) {
        return res.locals.partials = {
          password: 'example-password/password'
        };
      };
      app.peek.get('/login-example', load);
      return app.peek.post('/login-example', function(req, res) {
        console.log('Password: ' + req.body.password);
        return load(req, res);
      });
    }
  };

}).call(this);
