// Generated by CoffeeScript 1.7.1
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  define(['odo/messaging/hub', 'odo/express'], function(hub, express) {
    var Messaging;
    return Messaging = (function() {
      function Messaging() {
        this.sendcommand = __bind(this.sendcommand, this);
        this.web = __bind(this.web, this);
      }

      Messaging.prototype.web = function() {};

      Messaging.prototype.sendcommand = function(req, res) {
        if (req.user == null) {
          res.send(403, 'authentication required');
          return;
        }
        req.body.by = req.user.id;
        hub.send({
          command: req.params.command,
          payload: req.body
        });
        return res.send('Ok');
      };

      return Messaging;

    })();
  });

}).call(this);
