// Generated by IcedCoffeeScript 1.6.3-g
(function() {


  define(['redis'], function(redis) {
    var cmd, evt, result, subscriptions;
    cmd = redis.createClient();
    evt = redis.createClient();
    subscriptions = [];
    result = {
      emit: function(commandName, sender, message) {
        console.log("hub -- publishing command " + commandName + " to redis:");
        console.log(message);
        message = JSON.stringify(message, null, 4);
        return cmd.publish('commands', message);
      },
      on: function(channel, callback) {
        subscriptions.push({
          channel: channel,
          callback: callback
        });
        return console.log("hub -- subscribers: " + subscriptions.length);
      }
    };
    evt.on('message', function(channel, message) {
      console.log("hub -- received event " + message.event + " from redis:");
      message = JSON.parse(message);
      console.log(message);
      return subscriptions.forEach(function(subscriber) {
        if (channel === subscriber.channel) {
          return subscriber.callback(message);
        }
      });
    });
    evt.subscribe('events');
    return result;
  });

}).call(this);
