// Generated by IcedCoffeeScript 1.4.0c
(function() {
  var express;

  express = require('express');

  module.exports = {
    configure: function(app) {
      app.use('/js', express["static"](__dirname + '/js'));
      app.use('/css', express["static"](__dirname + '/css'));
      return app.use('/img', express["static"](__dirname + '/img'));
    }
  };

}).call(this);
