// Generated by IcedCoffeeScript 1.4.0c
(function() {
  var components, express;

  express = require('express');

  components = [require('./dashboard')];

  module.exports = {
    configure: function(app) {
      var component, _i, _len, _results;
      app.use('/js', express["static"](__dirname + '/js'));
      app.use('/css', express["static"](__dirname + '/css'));
      app.use('/img', express["static"](__dirname + '/img'));
      _results = [];
      for (_i = 0, _len = components.length; _i < _len; _i++) {
        component = components[_i];
        if (component.configure != null) {
          _results.push(component.configure(app));
        } else {
          _results.push(void 0);
        }
      }
      return _results;
    },
    init: function(app) {
      var component, _i, _len, _results;
      _results = [];
      for (_i = 0, _len = components.length; _i < _len; _i++) {
        component = components[_i];
        if (component.init != null) {
          _results.push(component.init(app));
        } else {
          _results.push(void 0);
        }
      }
      return _results;
    }
  };

}).call(this);
