// Generated by IcedCoffeeScript 1.4.0a
(function() {
  var fs, path, _;

  fs = require('fs');

  path = require('path');

  _ = require('underscore');

  module.exports = {
    init: function(app) {
      app.post('/%CF%88/components/:id', function(req, res) {
        var plugin;
        plugin = _(app.plugins).find(function(plugin) {
          return plugin.id === req.params.id;
        });
        if (plugin == null) {
          res.send(404);
          return;
        }
        if (req.body.disabled === 'true') {
          plugin.config.disabled = true;
        } else {
          delete plugin.config.disabled;
        }
        fs.writeFileSync(plugin.configpath, JSON.stringify(plugin.config, null, 2));
        return res.send('okay');
      });
      return app.get('/%CF%88/components/', function(req, res) {
        res.locals.plugins = app.plugins;
        return res.render('admin/layout', {
          title: 'Ψ -> Enable and disable components',
          bodyclasses: ['prompt'],
          partials: {
            content: 'components'
          }
        });
      });
    }
  };

}).call(this);
