// Generated by IcedCoffeeScript 1.4.0c
(function() {
  var fs, path, _;

  fs = require('fs');

  path = require('path');

  _ = require('underscore');

  module.exports = {
    init: function(app) {
      return app.get('/%CF%88/', function(req, res) {
        var adminplugin;
        adminplugin = _(app.plugins.root).find(function(plugin) {
          return plugin.id === 'admin';
        });
        res.locals.pluginsbycategory = _(adminplugin.plugins).filter(function(plugin) {
          return plugin.config.disabled !== true;
        });
        res.locals.pluginsbycategory = _(res.locals.pluginsbycategory).groupBy(function(plugin) {
          return plugin.config.category.toLowerCase();
        });
        return res.render({
          view: 'admin/layout',
          data: {
            title: 'Ψ',
            bodyclasses: ['full-admin']
          },
          partials: {
            content: 'dashboard'
          }
        });
      });
    }
  };

}).call(this);
