// Generated by IcedCoffeeScript 1.6.3-g
(function() {


  define(['module', 'path', 'express', 'redis'], function(module, path, express, redis) {
    return {
      configure: function(app) {
        return app.use('/eventstore', express["static"](path.dirname(module.uri) + '/public'));
      },
      init: function(app) {
        return app.post('/eventstore/event/:name', function(req, res) {
          console.log("" + req.params.name);
          return res.send(200);
        });
      }
    };
  });

}).call(this);
