// Generated by IcedCoffeeScript 1.4.0c
(function() {
  var _;

  _ = require('underscore');

  module.exports = {
    init: function(app) {
      return app.get("/%CF%88/fetch/", function(req, res) {
        var fetch, implementation, spec, specifications;
        res.locals.strategies = (function() {
          var _ref, _results;
          _ref = app.fetch.getAll();
          _results = [];
          for (fetch in _ref) {
            specifications = _ref[fetch];
            _results.push({
              name: fetch,
              specifications: (function() {
                var _results1;
                _results1 = [];
                for (spec in specifications) {
                  implementation = specifications[spec];
                  _results1.push({
                    name: spec
                  });
                }
                return _results1;
              })()
            });
          }
          return _results;
        })();
        return res.render({
          view: 'admin/layout',
          data: {
            title: 'Ψ -> Fetching strategies',
            bodyclasses: ['prompt']
          },
          partials: {
            content: 'fetch/fetch'
          }
        });
      });
    }
  };

}).call(this);
