// Generated by CoffeeScript 1.6.3
(function() {
  define(['jquery', 'q'], function($, Q) {
    var cache,
      _this = this;
    cache = null;
    return {
      getUser: function() {
        var dfd;
        dfd = Q.defer();
        if (_this.cache != null) {
          dfd.resolve(_this.cache);
        }
        Q($.get('/odo/auth/user')).then(function(data) {
          _this.cache = data;
          return dfd.resolve(data);
        }).fail(function() {
          return dfd.reject();
        });
        return dfd.promise;
      }
    };
  });

}).call(this);
