// Generated by CoffeeScript 1.6.3
(function() {
  define(['jquery', 'q'], function($, Q) {
    var cache,
      _this = this;
    cache = null;
    return {
      getUser: function() {
        var dfd;
        dfd = Q.defer();
        if (_this.cache != null) {
          dfd.resolve(_this.cache);
        }
        Q($.get('/odo/auth/user')).then(function(data) {
          _this.cache = data;
          return dfd.resolve(data);
        }).fail(function() {
          return dfd.reject();
        });
        return dfd.promise;
      },
      assignUsernameToUser: function(id, username) {
        return $.post('/sendcommand/assignUsernameToUser', {
          id: id,
          username: username
        });
      },
      assignDisplayNameToUser: function(id, displayName) {
        return $.post('/sendcommand/assignDisplayNameToUser', {
          id: id,
          displayName: displayName
        });
      },
      assignEmailAddressToUser: function(id, email) {
        return $.post('/sendcommand/assignEmailAddressToUser', {
          id: id,
          email: email
        });
      },
      getUsernameAvailability: function(username) {
        return $.get('/odo/auth/local/usernameavailability', {
          username: username
        });
      },
      testAuthentication: function(username, password) {
        return $.get('/odo/auth/local/test', {
          username: username,
          password: password
        });
      },
      assignPasswordToUser: function(id, password) {
        return $.post('/sendcommand/assignPasswordToUser', {
          id: id,
          password: password
        });
      },
      disconnectTwitterFromUser: function(id, profile) {
        return $.post('/sendcommand/disconnectTwitterFromUser', {
          id: id,
          profile: profile
        });
      },
      disconnectFacebookFromUser: function(id, profile) {
        return $.post('/sendcommand/disconnectFacebookFromUser', {
          id: id,
          profile: profile
        });
      },
      disconnectGoogleFromUser: function(id, profile) {
        return $.post('/sendcommand/disconnectGoogleFromUser', {
          id: id,
          profile: profile
        });
      },
      removeLocalSigninForUser: function(id, profile) {
        return $.post('/sendcommand/removeLocalSigninForUser', {
          id: id,
          profile: profile
        });
      }
    };
  });

}).call(this);
