// Generated by IcedCoffeeScript 1.4.0a
(function() {
  var express, passport;

  express = require('express');

  passport = require('passport');

  module.exports = {
    configure: function(app) {
      app.use(passport.initialize());
      return app.use(passport.session());
    }
  };

}).call(this);
