// Generated by CoffeeScript 1.6.3
(function() {
  define(['module', 'path', 'express', 'odo/hub', 'thomascoats.com/articlecontentprojection', 'thomascoats.com/articleownershipprojection'], function(module, path, express, hub, articlecontent, articleownership) {
    return {
      configure: function(app) {
        return app.use('/articles', express["static"](path.dirname(module.uri) + '/public'));
      },
      init: function(app) {
        app.get('/user/:id/articles', function(req, res) {
          if (req.user == null) {
            res.send(403, 'authentication required');
            return;
          }
          if (req.user.id !== req.params.id) {
            res.send(403, 'authentication required');
            return;
          }
          return articleownership.get(req.params.id, function(err, data) {
            var articles, id, name;
            if (err != null) {
              res.send(500, err);
              return;
            }
            if (data == null) {
              res.send(404, err);
              return;
            }
            articles = [];
            for (id in data) {
              name = data[id];
              articles.push({
                id: id,
                name: name,
                href: "article/" + id
              });
            }
            return res.send(articles);
          });
        });
        app.get('/article/:id', function(req, res) {
          if (req.user == null) {
            res.send(403, 'authentication required');
            return;
          }
          return articlecontent.get(req.params.id, function(err, article) {
            if (err != null) {
              res.send(500, err);
              return;
            }
            if (article == null) {
              res.send(404, err);
              return;
            }
            return articleownership.get(req.user.id, function(err, articles) {
              if (err != null) {
                res.send(500, err);
                return;
              }
              if (articles[req.params.id] == null) {
                res.send(403, 'authentication required');
                return;
              }
              return res.send(article);
            });
          });
        });
        app.post('/article/:id', function(req, res) {
          if (req.user == null) {
            res.send(403, 'authentication required');
            return;
          }
          hub.send({
            command: 'createArticle',
            payload: {
              id: req.params.id,
              name: req.body.name,
              by: req.user.id
            }
          });
          return res.send('Ok');
        });
        return app["delete"]('/article/:id', function(req, res) {
          if (req.user == null) {
            res.send(403, 'authentication required');
            return;
          }
          return articleownership.get(req.user.id, function(err, articles) {
            if (err != null) {
              res.send(500, err);
              return;
            }
            if (articles[req.params.id] == null) {
              res.send(403, 'authentication required');
              return;
            }
            hub.send({
              command: 'deleteArticle',
              payload: {
                id: req.params.id,
                by: req.user.id
              }
            });
            return res.send('Ok');
          });
        });
      }
    };
  });

}).call(this);
