// Generated by CoffeeScript 1.6.3
(function() {
  var __slice = [].slice;

  define(['odo/plugins', 'odo/user/usercommands', 'odo/user/userprofile'], function() {
    var Plugins, plugins;
    Plugins = arguments[0], plugins = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
    return new Plugins(plugins);
  });

}).call(this);
